### ISSUE TITLE
Variable Pred1 is never used

### ISSUE THREAD

**Issue by dvorst** [NoviceMAn-prog/MSRF-Net#10]
Pred1 is never used
https://github.com/NoviceMAn-prog/MSRF-Net/blob/23e5bf428276cfab6eaed3922465feb275ba9c66/model.py#L175

This means that lines 171, 172, 173, 174 & 175 cause computational overhead

**Comment by NoviceMAn-prog** [comment]
Yes, it is never used, will soon upload a cleaner version.
