### ISSUE TITLE
Encoder blocks are not the same

### ISSUE THREAD

**Issue by dvorst** [NoviceMAn-prog/MSRF-Net#11]
The equation for encoder block 'x' can be written as:
nx1 = Conv(ReLU(Conv(ReLU(BN(SE( input ))))))
nx2 = nx1 + Conv(BN(nx1))
poolx = maxpool( dropout( nx2 ))

The first equation (nx1) is as described in the paper. The second however, which is basically a residual block, is not described in the paper and only used by encoder blocks 2 and 3.

Is this intentional?

**Comment by NoviceMAn-prog** [comment]
Even though nx2 is mentioned in the model designed, it is neither used for pooling nor by the MSRF sub-network (it is never used), hence it follows the description mentioned in the paper
