### ISSUE TITLE
sau was not defined

### ISSUE THREAD

**Issue by NSAVALAN** [NoviceMAn-prog/MSRF-Net#2]
Hi,

thanks for sharing this. when I run the trian.py I get this error: 
**************************************************************************
"G = sau()
Traceback (most recent call last):

  File "<ipython-input-6-18c862362c20>", line 1, in <module>
    G = sau()

NameError: name 'sau' is not defined"
****************************************************************************************
I can see that there is a function named sau in the msrf.py. would you please help me to fix this.

Regards

**Comment by JiayuZou-home** [comment]
It seems that we should add a new axis on the second dimension first and then add another new axis on the third dimension.

**Comment by puzhong-hug** [comment]
> It seems that we should add a new axis on the second dimension first and then add another new axis on the third dimension.

Hello, have you reappeared? I met the same problem,name 'att' is not defined

**Comment by NoviceMAn-prog** [comment]
Hey I have updated the code and fixed all the issues, please check
