### ISSUE TITLE
I can't get the correct version of each python package

### ISSUE THREAD

**Issue by BESTTOOLBOX** [NoviceMAn-prog/MSRF-Net#28]
I want to try the code but I can't get the correct version of each python package. They conflict with each other. Can someone share the correct "pip list" or "conda list"? 
Thank you so much

**Comment by augustoicaro** [comment]
It uses tensorflow 2+, due to Cuda version limitations I upgraded the code to tensorflow 2.4.0 and used cuddn and cudatoolkit from conda. I will fork the repo tomorrow and upload my modifications. Then I will send here the repo link with the environment requirements.

But overall the code it is a little bit messy and have some mistakes. If you use pytorch I suggest you to use the pytorch fork that someone did and shared at the issues.

**Comment by BESTTOOLBOX** [comment]
Thanks so much. Looking forward to your code.



---- 回复的原邮件 ----
| 发件人 | Augusto Ícaro Farias da ***@***.***> |
| 日期 | 2022年02月20日 22:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NoviceMAn-prog/MSRF-Net] I can't get the correct version of each python package (Issue #28) |

It uses tensorflow 2+, due to Cuda version limitations I upgraded the code to tensorflow 2.4.0 and used cuddn and cudatoolkit from conda. I will fork the repo tomorrow and upload my modifications. Then I will send here the repo link with the environment requirements.

But overall the code it is a little bit messy and have some mistakes. If you use pytorch I suggest you to use the pytorch fork that someone did and shared at the issues.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by augustoicaro** [comment]
@BESTTOOLBOX, sorry for my late response. Here is my repo with my modifications: https://github.com/augustoicaro/MSRF-Net

**Comment by BESTTOOLBOX** [comment]
Thanks so much.
















At 2022-02-23 03:09:40, "Augusto Ícaro Farias da Cunha" ***@***.***> wrote:

@BESTTOOLBOX, sorry for my late response. Here is my repo with my modifications: https://github.com/augustoicaro/MSRF-Net

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BESTTOOLBOX** [comment]
@augustoicaro Thanks for your help. I can run it successfully.
