### ISSUE TITLE
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[[0., 0., 0.],

### ISSUE THREAD

**Issue by forestlin7** [NoviceMAn-prog/MSRF-Net#3]
when run to    "G.train_on_batch(x=[X_batch,edge_x],y=[Y_batch,edge_y,Y_batch,Y_batch])"
it will cause the following errors:
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],...

how to modify the error?

**Comment by NoviceMAn-prog** [comment]
The model takes the input of images and their corresponding canny edges, however, in this case the model is expecting a single input of images. Try with the updated codes, should fix the issue.
