### ISSUE TITLE
How to get the Ground Truth of the contour of the image

### ISSUE THREAD

**Issue by WangZhi-wz** [NoviceMAn-prog/MSRF-Net#34]
![image](https://user-images.githubusercontent.com/74870759/207868577-a26ddf4e-143d-43de-9f5d-b881032efb31.png)
How to get the Ground Truth of the contour of the image

**Comment by augustoicaro** [comment]
Hello @MOONWZ,

This network as you can see in the model code has 4 output(pred, pred2, pred4, and edges). When you predict a image the result will be a tuple. Just look for last member of this tuple and the shape stream result will be there.

**Comment by WangZhi-wz** [comment]
> Hello @MOONWZ,
> 
> This network as you can see in the model code has 4 output(pred, pred2, pred4, and edges). When you predict a image the result will be a tuple. Just look for last member of this tuple and the shape stream result will be there.

Oh, well, Thank you very much @augustoicaro
