### ISSUE TITLE
NameError: name 'att' is not defined

### ISSUE THREAD

**Issue by xiaojun-mbed** [NoviceMAn-prog/MSRF-Net#4]
When I run train.py, the name 'att' and 'pred8' are not defined at line 468 in model.py .

**Comment by moyaojunshi** [comment]
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    from msrf import sau
  File "/MSRF-Net/msrf.py", line 668, in <module>
    G = sau()
  File "/MSRF-Net/msrf.py", line 594, in sau
    model = Model(inputs= [inputs_img,att],outputs = [x,pred2,pred4,pred8])
NameError: name 'att' is not defined

**Comment by NoviceMAn-prog** [comment]
Hey, use the latest version of the code, all issues related to missing variables are fixed.
