### ISSUE TITLE
PyTorch implementation

### ISSUE THREAD

**Issue by amlarraz** [NoviceMAn-prog/MSRF-Net#7]
Hi  @NoviceMAn-prog I'm trying to reproduce your code (only the model part) in PyTorch. However seems like your code isn't debbuged and tested, is it? As I cann see in other issues and as I've seen  during my forst try to reproduce, there are a lot of problems to fix. 

Did you train a model with this code? If not please let us know,

Thank you in advance,

**Comment by amlarraz** [comment]
Hi @NoviceMAn-prog , I've developed a version of MSRF-Net in PyTorch. I've not the training code yet (It's in my roadmap so I expect to release it soon). However if you or someone want to see the clean model code you can find it [here](https://github.com/amlarraz/MSRF-Net_PyTorch). I've clean and debug the code using both your model code and your training code.

Any suggestions will be appreciated.

**Comment by NoviceMAn-prog** [comment]
Hey, you can follow my GMSRF-Net repo, where dense global multi-scale fusion is performed using PyTorch.

**Comment by amlarraz** [comment]
@NoviceMAn-prog hello! Thanks for your awesome work btw! Yep, I've just discovered this repo searching on the internet. Many thanks for the advice!
