### ISSUE TITLE
Output of three DSDF blocks get overwritten

### ISSUE THREAD

**Issue by dvorst** [NoviceMAn-prog/MSRF-Net#8]
**Issue:**
Currently the output of lines 228, 230 & 232 gets overwritten, see image.
![tmp](https://user-images.githubusercontent.com/87502756/151669271-4024fe84-bf74-40bb-8bbe-603e35aee2c3.png)

**Proposed solution 1:**
Change input of line 234 to `n13,n23` 
https://github.com/NoviceMAn-prog/MSRF-Net/blob/23e5bf428276cfab6eaed3922465feb275ba9c66/model.py#L234

Change input of line 236 to `n33, n43`
https://github.com/NoviceMAn-prog/MSRF-Net/blob/23e5bf428276cfab6eaed3922465feb275ba9c66/model.py#L236

**Proposed solution 2:**
Alternatively, lines 232, 234 & 236 can be commented out to remove computational overhead.

**Comment by NoviceMAn-prog** [comment]
In Keras, such scenarios do not lead to computational overhead as only the end-to-end architecture is considered, if it is overwritten only the last architecture declaration will be computed and contribute to model parameters
