### ISSUE TITLE
output of shape stream is not used

### ISSUE THREAD

**Issue by dvorst** [NoviceMAn-prog/MSRF-Net#9]
The output of the shape stream (line below) is not used

https://github.com/NoviceMAn-prog/MSRF-Net/blob/23e5bf428276cfab6eaed3922465feb275ba9c66/model.py#L273

**Comment by NoviceMAn-prog** [comment]
Thank you for bringing this to my attention, I have fixed the error (Note edge_out is supervised using the GT edges, and then it is combined with the image gradients and concatenated with the last decoder block)
